<?xml version="1.0"?>

<description 
	targetNamespace="http://example.com/stockquote.wsdl"
	xmlns:tns="http://example.com/stockquote.wsdl"
	xmlns:xsd1="http://example.com/stockquote.xsd"
	xmlns:wsoap=" http://www.w3.org/2004/08/wsdl/soap12"
	xmlns=" http://www.w3.org/2004/08/wsdl">

    <types>
       <schema targetNamespace="http://example.com/stockquote.xsd" xmlns="http://www.w3.org/2000/10/XMLSchema">
           <element name="TradePriceRequest">
              <complexType>
                  <all>
                      <element name="tickerSymbol" type="string"/>
                  </all>
              </complexType>
           </element>
           <element name="TradePrice">
              <complexType>
                  <all>
                      <element name="price" type="float"/>
                  </all>
              </complexType>
           </element>
       </schema>
    </types>

    <interface name="StockQuote">
		<operation name="GetLastTradePrice" pattern="http://www.w3.org/2004/03/wsdl/in-out">
           <input messageLabel="In" element="xsd1:TradePriceRequest"/>
           <output messageLabel="Out" element="xsd1:TradePrice"/>
        </operation>
    </interface>

    <binding 
		name="StockQuoteSoapBinding" 
		interface="tns:StockQuote" 
		type ="http://www.w3.org/2004/08/wsdl/soap12"
        wsoap:protocol="http://www.w3.org/2003/05/soap/bindings/HTTP"
        wsoap:mepDefault="http://www.w3.org/2003/05/soap/mep/request-response">

        <operation ref="tns:GetLastTradePrice" wsoap:action="http://example.com/GetLastTradePrice"/>

    </binding>

    <service name="StockQuoteService" interface="tns:StockQuote">
        <documentation>My first service</documentation>
        <endpoint name="StockQuotePort"  binding="tns:StockQuoteBinding" address ="http://example.com/stockquote"/>
    </service>

</description>