package org.fabric3.tests.binding.metro.weather;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAXWS SI. JAX-WS RI 2.0_03-b24-fcs Generated source version: 2.0
 */
@WebFault(name = "weatherFault", targetNamespace = "urn:weather")
public class WeatherFaultException
        extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     */
    private WeatherFault faultInfo;

    /**
     * @param faultInfo
     * @param message
     */
    public WeatherFaultException(String message, WeatherFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * @param faultInfo
     * @param message
     * @param cause
     */
    public WeatherFaultException(String message, WeatherFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * @return returns fault bean: weather.WeatherFault
     */
    public WeatherFault getFaultInfo() {
        return faultInfo;
    }

}
