
package org.fabric3.tests.binding.metro.weather;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.5-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WeatherPortType", targetNamespace = "urn:weather")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WeatherPortType {


    /**
     * 
     * @param weatherRequest
     * @return
     *     returns weather.WeatherResponse
     */
    @WebMethod
    @WebResult(name = "weatherResponse", targetNamespace = "urn:weather", partName = "weatherResponse")
    public WeatherResponse getWeather(
        @WebParam(name = "weatherRequest", targetNamespace = "urn:weather", partName = "weatherRequest")
        WeatherRequest weatherRequest);

}
