package org.fabric3.tests.binding.metro.weather;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAXWS SI. JAX-WS RI 2.0_03-b24-fcs Generated source version: 2.0
 */
@WebService(name = "WeatherPortType", targetNamespace = "urn:weather")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WeatherPortType {


    /**
     * @param weatherRequest
     * @return returns weather.WeatherResponse
     * @throws WeatherFaultException
     */
    @WebMethod
    @WebResult(name = "weatherResponse", targetNamespace = "urn:weather", partName = "weatherResponse")
    public WeatherResponse getWeather(
            @WebParam(name = "weatherRequest", targetNamespace = "urn:weather", partName = "weatherRequest")
            WeatherRequest weatherRequest)
            throws WeatherFaultException
            ;

}
